[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "FinePhrase"
version = "0.1.0"
description = "Generate fine-grained n-gram embeddings with transformers."
readme = "README.md"
authors = [
  {name = "Nicholas Gigliotti", email = "ndgigliotti@gmail.com"}
]
maintainers = [
  {name = "Nicholas Gigliotti", email = "ndgigliotti@gmail.com"}
]
classifiers = [

]
license = {text = "Apache-2.0"}
dependencies = [

]

[project.optional-dependencies]
dev = [
    "coverage",  # testing
    "mypy",  # linting
    "pytest",  # testing
    "ruff"  # linting
]

[project.urls]

bugs = "https://github.com/ndgigliotti/finephrase/issues"
changelog = "https://github.com/ndgigliotti/finephrase/blob/master/changelog.md"
homepage = "https://github.com/ndgigliotti/finephrase"

[tool.setuptools]
packages = ["finephrase"]

[tool.setuptools.package-data]
"*" = ["*.*"]




# Mypy
# ----

[tool.mypy]
files = "."

# Use strict defaults
strict = true
warn_unreachable = true
warn_no_return = true

[[tool.mypy.overrides]]
# Don't require test functions to include types
module = "tests.*"
ignore_missing_imports = true
